[package]
name = "wgman"
version = "0.1.0"
authors = ["ashley"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = { git = "https://github.com/seanmonstar/warp" }
ring = "0.16.19"
data-encoding = "2.3.1"
mobc = "0.7.0"
mobc-postgres = "0.7.0"